---
- name: firewalld open tcp 80 port
  become: yes
  become_user: root
  firewalld:
    immediate: true
    permanent: true
    service: http
    state: enabled

- name: Put default-h2o.conf
  become: yes
  become_user: root
  copy:
    src: default-h2o.conf
    dest: /etc/h2o/default-h2o.conf

- name: Put php-h2o.conf
  become: yes
  become_user: root
  copy:
    src: php-h2o.conf
    dest: /etc/h2o/php-h2o.conf

- name: Remove h2o.conf
  become: yes
  become_user: root
  file:
    state: absent
    path: /etc/h2o/h2o.conf

- name: Put h2o.conf link
  become: yes
  become_user: root
  file:
    state: link
    src: /etc/h2o/default-h2o.conf
    dest: /etc/h2o/h2o.conf
- name: Put torb.nodejs.service	
  become: yes	
  become_user: root	
  copy:	
    src: torb.nodejs.service	
    dest: /etc/systemd/system/torb.nodejs.service
- name: Install for torb.nodejs	
  become: yes	
  become_user: isucon	
  args:	
    chdir: /home/isucon/torb/webapp/nodejs	
  shell: |	
    bash -lc "/home/isucon/local/node/bin/npm install"
